contames/src/main/java/br/com/contames/entity/LancamentoFatura.java
package br.com.contames.entity;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

/**
 * Entity implementation class for Entity: LancamentoFatura
 *
 */
@Entity
public class LancamentoFatura implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@SequenceGenerator(name = "lancamentofatura_seq", sequenceName = "lancamentofatura_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "lancamentofatura_seq")
    private Long id;

	@ManyToOne
	@NotNull(message = "{lancamento.notNull}")
	@JoinColumn(updatable = false)
	private Lancamento lancamento;
	
	@NotNull(message = "{seq.notNull}")
	@Min(value = 0, message = "{seq.min}")
	@Column(nullable = false)
	private Integer seq;
	
	@OneToOne
	@JoinColumn(updatable = false)
	private LancamentoParcela lancamentoParcela;
	
	@OneToOne
	@JoinColumn(updatable = false)
	private Transferencia transferencia;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}

	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public LancamentoParcela getLancamentoParcela() {
		return lancamentoParcela;
	}

	public void setLancamentoParcela(LancamentoParcela lancamentoParcela) {
		this.lancamentoParcela = lancamentoParcela;
	}
	
	public Transferencia getTransferencia() {
		return transferencia;
	}

	public void setTransferencia(Transferencia transferencia) {
		this.transferencia = transferencia;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final LancamentoFatura other = (LancamentoFatura) obj;
		if (id != other.id && (id == null || !id.equals(other.id))) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 17 * hash + (this.id != null ? this.id.hashCode() : 0);
		return hash;
	}
	
	@Override
    public String toString() {
        return String.valueOf(id);
    }
   
}

contames/src/main/java/br/com/contames/entity/LancamentoParcela.java
package br.com.contames.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Transient;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.joda.time.LocalDate;

import br.com.contames.enumeration.BoletoTipo;
import br.com.contames.enumeration.ItemTipo;
import br.com.contames.enumeration.LancamentoStatus;
import br.com.contames.enumeration.MeioPagamento;
import br.com.contames.util.NumericHelper;
import br.com.contames.util.StringHelper;

@Entity
public class LancamentoParcela implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@SequenceGenerator(name = "lancamentoparcela_seq", sequenceName = "lancamentoparcela_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "lancamentoparcela_seq")
    private Long id;

	@ManyToOne
	@NotNull(message = "{lancamento.notNull}")
	@JoinColumn(updatable = false)
	private Lancamento lancamento;
	
	@OneToMany(mappedBy = "lancamentoParcela")
	private List<Arquivo> arquivoList = new ArrayList<Arquivo>();
	
	@OneToOne(mappedBy = "lancamentoParcela")
	private BaixaItem baixaItem;
	
	@NotNull(message = "{seq.notNull}")
	@Min(value = 0, message = "{seq.min}")
	@Column(nullable = false)
	private Integer seq;
	
	@NotNull(message = "{data.notNull}")
	@Column(name = "_data", nullable = false)
	private LocalDate data;
	
	@NotNull(message = "{meio.notNull}")
	@Enumerated(EnumType.STRING)
	@Column(length = 7, nullable = false)
	private MeioPagamento meio;
	
	@ManyToOne
	private CartaoCredito cartaoCredito;
	
	private Boolean isLimite;
	
	@ManyToOne
	private Conta conta;
	
	@OneToOne
	private Cheque cheque;
	
	@Enumerated(EnumType.STRING)
	@Column(length = 8)
	private BoletoTipo boletoTipo;
	
	@Size(max = 54, message = "{boletoNumero.size}")
	@Column(length = 54)
	private String boletoNumero;
	
	@ManyToOne
	private Arquivo arquivo;
	
	@Size(max = 400, message = "{obs.size}")
	@Column(length = 400)
	private String obs;
	
	@NotNull(message = "{valor.notNull}")
	@Column(nullable = false)
	private Double valor;
	
	@NotNull(message = "{perc.notNull}")
	@Column(nullable = false)
	private Double perc;
	
	@NotNull(message = "{tipo.notNull}")
	@Enumerated(EnumType.STRING)
	@Column(nullable = false, updatable = false)
	private ItemTipo tipo;
	
	@NotNull(message = "{status.notNull}")
	@Enumerated(EnumType.STRING)
	@Column(length = 3, nullable = false)
	private LancamentoStatus status;
	
	@Transient
	private String viewid;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}
	
	public List<Arquivo> getArquivoList() {
		return arquivoList;
	}

	public void setArquivoList(List<Arquivo> arquivoList) {
		this.arquivoList = arquivoList;
	}

	public BaixaItem getBaixaItem() {
		return baixaItem;
	}

	public void setBaixaItem(BaixaItem baixaItem) {
		this.baixaItem = baixaItem;
	}

	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public LocalDate getData() {
		return data;
	}

	public void setData(LocalDate data) {
		this.data = data;
	}

	public MeioPagamento getMeio() {
		return meio;
	}

	public void setMeio(MeioPagamento meio) {
		this.meio = meio;
	}
	
	public CartaoCredito getCartaoCredito() {
		return cartaoCredito;
	}

	public void setCartaoCredito(CartaoCredito cartaoCredito) {
		this.cartaoCredito = cartaoCredito;
	}
	
	public Boolean getIsLimite() {
		return isLimite;
	}

	public void setIsLimite(Boolean isLimite) {
		this.isLimite = isLimite;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.conta = conta;
	}

	public Cheque getCheque() {
		return cheque;
	}

	public void setCheque(Cheque cheque) {
		this.cheque = cheque;
	}

	public BoletoTipo getBoletoTipo() {
		return boletoTipo;
	}

	public void setBoletoTipo(BoletoTipo boletoTipo) {
		this.boletoTipo = boletoTipo;
	}

	public String getBoletoNumero() {
		return boletoNumero;
	}

	public void setBoletoNumero(String boletoNumero) {
		this.boletoNumero = boletoNumero;
	}
	
	public Arquivo getArquivo() {
		return arquivo;
	}

	public void setArquivo(Arquivo arquivo) {
		this.arquivo = arquivo;
	}

	public String getObs() {
		return obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	public Double getValor() {
		return valor;
	}

	public void setValor(Double valor) {
		this.valor = NumericHelper.around(valor);
	}
	
	public Double getPerc() {
		return perc;
	}

	public void setPerc(Double perc) {
		this.perc = perc;
	}

	public ItemTipo getTipo() {
		return tipo;
	}

	public void setTipo(ItemTipo tipo) {
		this.tipo = tipo;
	}
	
	public LancamentoStatus getStatus() {
		return status;
	}

	public void setStatus(LancamentoStatus status) {
		this.status = status;
	}
	
	public String getViewid() {
		if(viewid == null) {
			viewid = StringHelper.createViewId();
		}
		return viewid;
	}

	public void setViewid(String viewid) {
		this.viewid = viewid;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final LancamentoParcela other = (LancamentoParcela) obj;
		if (id != other.id && (id == null || !id.equals(other.id))) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 17 * hash + (this.id != null ? this.id.hashCode() : 0);
		return hash;
	}
	
	@Override
    public String toString() {
        return String.valueOf(id);
    }
	
	public String getParcelaDisplay() {
		
		if(lancamento != null) {
			if(lancamento.getQuantLancamentoParcela().equals(1)) {
				return "-";
			} else {
				return (getSeq() + 1) + " / " + lancamento.getQuantLancamentoParcela();
			}
		}
		
		return null;
	}
	
}

contames/src/main/java/br/com/contames/entity/LancamentoRateio.java
package br.com.contames.entity;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Transient;
import javax.validation.constraints.DecimalMax;
import javax.validation.constraints.DecimalMin;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;

import br.com.contames.enumeration.LancamentoRateioTipo;
import br.com.contames.util.NumericHelper;
import br.com.contames.util.StringHelper;

@Entity
public class LancamentoRateio implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@SequenceGenerator(name = "lancamentorateio_seq", sequenceName = "lancamentorateio_seq", allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "lancamentorateio_seq")
    private Long id;
	
	@ManyToOne
	@NotNull(message = "{lancamento.notNull}")
	@JoinColumn(updatable = false, nullable = false)
	private Lancamento lancamento;
	
	@OneToMany(mappedBy = "lancamentoRateio")
	private List<Arquivo> arquivoList = new ArrayList<Arquivo>();
	
	@NotNull(message = "{lancamentoRateio.tipo.notNull}")
	@Enumerated(EnumType.STRING)
	@Column(length = 3, nullable = false)
	private LancamentoRateioTipo tipo;
	
	@ManyToOne
	private Pessoa pessoa;
	
	@ManyToOne
	private Descricao rateio;
	
	@NotNull(message = "{seq.notNull}")
	@Min(value = 0, message = "{seq.min}")
	@Column(nullable = false)
	private Integer seq;
	
	@NotNull(message = "{perc.notNull}")
	@DecimalMin(value = "0.00", message="{perc.min}")
	@DecimalMax(value = "100.00", message = "{perc.max}")
	@Column(nullable = false)
	private Double perc;
	
	@NotNull(message = "{valor.notNull}")
	@Column(nullable = false)
	private Double valor;
	
	@NotNull(message = "{perc.notNull}")
	@Column(nullable = false)
	private Double percCalc;
	
	@Transient
	private String viewid;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Lancamento getLancamento() {
		return lancamento;
	}

	public void setLancamento(Lancamento lancamento) {
		this.lancamento = lancamento;
	}
	
	public List<Arquivo> getArquivoList() {
		return arquivoList;
	}

	public void setArquivoList(List<Arquivo> arquivoList) {
		this.arquivoList = arquivoList;
	}

	public LancamentoRateioTipo getTipo() {
		return tipo;
	}

	public void setTipo(LancamentoRateioTipo tipo) {
		this.tipo = tipo;
	}

	public Pessoa getPessoa() {
		return pessoa;
	}

	public void setPessoa(Pessoa pessoa) {
		this.pessoa = pessoa;
	}

	public Descricao getRateio() {
		return rateio;
	}

	public void setRateio(Descricao rateio) {
		this.rateio = rateio;
	}

	public Integer getSeq() {
		return seq;
	}

	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	public Double getPerc() {
		return perc;
	}

	public void setPerc(Double perc) {
		this.perc = NumericHelper.around(perc);
	}

	public Double getValor() {
		return valor;
	}

	public void setValor(Double valor) {
		this.valor = NumericHelper.around(valor);
	}
	
	public Double getPercCalc() {
		return percCalc;
	}

	public void setPercCalc(Double percCalc) {
		this.percCalc = percCalc;
	}
	
	public String getViewid() {
		if(viewid == null) {
			viewid = StringHelper.createViewId();
		}
		return viewid;
	}

	public void setViewid(String viewid) {
		this.viewid = viewid;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}
		if (this == obj) {
			return true;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		final LancamentoRateio other = (LancamentoRateio) obj;
		if (id != other.id && (id == null || !id.equals(other.id))) {
			return false;
		}
		return true;
	}

	@Override
	public int hashCode() {
		int hash = 7;
		hash = 17 * hash + (this.id != null ? this.id.hashCode() : 0);
		return hash;
	}
	
	@Override
    public String toString() {
        return String.valueOf(id);
    }
	
	public String getDisplayNome() {
		if(LancamentoRateioTipo.PES.equals(tipo)) {
			if(pessoa != null && pessoa.getDisplayNome() != null) {
				return pessoa.getDisplayNome();
			}
		} else if(LancamentoRateioTipo.RAT.equals(tipo)) {
			if(rateio != null && rateio.getNome() != null) {
				return rateio.getNome();
			}
		}
		return null;
	}
	
}

contames/src/main/webapp/WEB-INF/jsp/lancamento/lancamentoFaturaList.jsp
<fmt:message key="patternDate" var="patternDate" />
<div id="layLancamentoFaturaList">
	<c:if test="${lancamentoFaturaList eq null or empty lancamentoFaturaList}">
		<div class="alert alert-success text-center cm-table-notfound" role="alert">
			<strong>
				<i class="fa fa-info-circle"></i>
				<fmt:message key="nenhumMovimentoEncontrado"/>
			</strong>
		</div>
	</c:if>
	<c:if test="${lancamentoFaturaList ne null and !empty lancamentoFaturaList}">
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th class="cm-th"><fmt:message key="n_"/></th>
						<th class="cm-th"><fmt:message key="data"/></th>
						<th class="cm-th"><fmt:message key="descricao"/></th>
						<th class="cm-th"><fmt:message key="parcela"/></th>
						<th class="cm-th"><fmt:message key="valor"/></th>
					</tr>
				</thead>
				<tbody id="tbyLancamentoFaturaList">
					<c:forEach var="lancamentoFatura" items="${lancamentoFaturaList}">
						<c:if test="${lancamentoFatura.lancamentoParcela ne null}">
							<tr 
								data-id="${lancamentoFatura.id}" 
								data-index="${lancamentoFatura.seq}" 
								data-lancamento-parcela="${lancamentoFatura.lancamentoParcela.id}"
								onclick="selecionarLancamentoFatura(this)">
								<td class="text-right">${lancamentoFatura.seq + 1}</td>
								<td class="text-center"><joda:format pattern="${patternDate}" value="${lancamentoFatura.lancamentoParcela.data}" /></td>
								<td><c:out value="${lancamentoFatura.lancamentoParcela.lancamento.favorecido.displayNome}" /></td>
								<td class="text-center">${lancamentoFatura.lancamentoParcela.parcelaDisplay}</td>
								<td class="text-right"><fmt:formatNumber type="number" value="${lancamentoFatura.lancamentoParcela.baixaItem eq null ? lancamentoFatura.lancamentoParcela.valor : lancamentoFatura.lancamentoParcela.baixaItem.valor}" maxFractionDigits="2" minFractionDigits="2" /></td>
							</tr>
						</c:if>
						<c:if test="${lancamentoFatura.transferencia ne null}">
							<tr 
								data-id="${lancamentoFatura.id}" 
								data-index="${lancamentoFatura.seq}" 
								data-transferencia="${lancamentoFatura.transferencia.id}"
								onclick="selecionarLancamentoFatura(this)">
								<td class="text-right">${lancamentoFatura.seq + 1}</td>
								<td class="text-center"><joda:format pattern="${patternDate}" value="${lancamentoFatura.transferencia.data}" /></td>
								<td><fmt:message key="transf_" />&nbsp;<c:out value="${lancamentoFatura.transferencia.cartaoCredito.nome}"/>&nbsp;<fmt:message key="p_" />&nbsp;<c:out value="${lancamentoFatura.transferencia.destino.nome}"/></td>
								<td class="text-center">-</td>
								<td class="text-right"><fmt:formatNumber type="number" value="${lancamentoFatura.transferencia.valor}" maxFractionDigits="2" minFractionDigits="2" /></td>
							</tr>
						</c:if>
					</c:forEach>
				</tbody>
				<tfoot>
					<tr class="cm-tr-total">
						<td class="text-right" colspan="4"><fmt:message key="total"/> :</td>
						<td class="text-right" id="lbTotalLancamentoFatura"><fmt:formatNumber type="number" value="${lancamento.totalLancamentoFatura}" maxFractionDigits="2" minFractionDigits="2" /></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</c:if>
</div>

contames/src/main/webapp/WEB-INF/jsp/lancamento/lancamentoItemList.jsp
<fmt:message key="patternDate" var="patternDate" />
<div id="layLancamentoItemList">
	<c:if test="${lancamentoItemList eq null or empty lancamentoItemList}">
		<div class="alert alert-success text-center cm-table-notfound" role="alert">
			<strong>
				<i class="fa fa-info-circle"></i>
				<c:choose>
					<c:when test="${lancamento.tipo eq 'DES'}">
						<fmt:message key="nenhumaDespesaEncontrada"/>
					</c:when>
					<c:when test="${lancamento.tipo eq 'REC'}">
						<fmt:message key="nenhumaReceitaEncontrada"/>
					</c:when>
					<c:otherwise>
						<fmt:message key="nenhumProdutoEncontrado"/>
					</c:otherwise>
				</c:choose>
			</strong>
		</div>
	</c:if>
	<c:if test="${lancamentoItemList ne null and !empty lancamentoItemList}">
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th class="cm-th"><fmt:message key="n_"/></th>
						<th class="cm-th"><fmt:message key="descricao"/></th>
						<th class="cm-th"><fmt:message key="obs"/></th>
						<th class="cm-th"><fmt:message key="qtde"/></th>
						<th class="cm-th"><fmt:message key="vlrUnit"/></th>
						<th class="cm-th"><fmt:message key="valor"/></th>
						<th class="cm-th"><fmt:message key="desconto"/></th>
						<th class="cm-th"><fmt:message key="total"/></th>
					</tr>
				</thead>
				<tbody id="tbyLancamentoItemList">
					<c:forEach var="lancamentoItem" items="${lancamentoItemList}" varStatus="st">
						<tr data-id="${lancamentoItem.id}" data-index="${lancamentoItem.seq}" data-item-id="${lancamentoItem.item.id}" onclick="selecionaLancamentoItem(this)" ondblclick="editarLancamentoItem(this)">
							<td class="text-right">${lancamentoItem.seq + 1}</td>
							<td>${lancamentoItem.item.displayName}</td>
							<td class="text-right"><c:out value="${lancamentoItem.obs}"/></td>
							<td class="text-right"><c:if test="${lancamentoItem.quant ne null}"><fmt:formatNumber type="number" value="${lancamentoItem.quant}" maxFractionDigits="3" minFractionDigits="3"/></c:if></td>
							<td class="text-right"><c:if test="${lancamentoItem.valorUnit ne null}"><fmt:formatNumber type="number" value="${lancamentoItem.valorUnit}" maxFractionDigits="2" minFractionDigits="2" /></c:if></td>
							<td class="text-right"><c:if test="${lancamentoItem.valor ne null}"><fmt:formatNumber type="number" value="${lancamentoItem.valor}" maxFractionDigits="2" minFractionDigits="2" /></c:if></td>
							<td class="text-right"><c:if test="${lancamentoItem.desconto ne null}"><fmt:formatNumber type="number" value="${lancamentoItem.desconto}" maxFractionDigits="2" minFractionDigits="2" /></c:if></td>
							<td class="text-right"><c:if test="${lancamentoItem.total ne null}"><fmt:formatNumber type="number" value="${lancamentoItem.total}" maxFractionDigits="2" minFractionDigits="2" /></c:if></td>
						</tr>
					</c:forEach>
				</tbody>
				<tfoot>
					<tr class="cm-tr-total">
						<td colspan="3" class="text-right"><fmt:message key="total"/> :</td>
						<td class="text-right"><fmt:formatNumber type="number" value="${lancamento.totalLancamentoItemQuant}" maxFractionDigits="3" minFractionDigits="3" /></td>
						<td class="text-right"><fmt:formatNumber type="number" value="${lancamento.totalLancamentoItemValorUnit}" maxFractionDigits="2" minFractionDigits="2" /></td>
						<td class="text-right"><fmt:formatNumber type="number" value="${lancamento.totalLancamentoItemValor}" maxFractionDigits="2" minFractionDigits="2" /></td>
						<td class="text-right">
							<c:choose>
								<c:when test="${lancamento.totalLancamentoItemDesconto eq 0}">&nbsp;</c:when>
								<c:otherwise>
									<fmt:formatNumber type="number" value="${lancamento.totalLancamentoItemDesconto}" maxFractionDigits="2" minFractionDigits="2" />		
								</c:otherwise>
							</c:choose>
						</td>
						<td class="text-right" id="lbTotalLancamentoItem"><fmt:formatNumber type="number" value="${lancamento.totalLancamentoItem}" maxFractionDigits="2" minFractionDigits="2" /></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</c:if>
</div>
<c:if test="${lancamentoItemList ne null and !empty lancamentoItemList and fn:length(lancamentoItemList) eq 1 and lancamentoItemList[0].item.favorecido ne null}">
	<script type="text/javascript">
		$(function() {
			if(!$('#lancFavorecido').data('val')) {
				$('#lancFavorecido')
					.data('val', '${lancamentoItemList[0].item.favorecido.id}')
					.val('${lancamentoItemList[0].item.favorecido.displayNome}')
					.prev().val('${lancamentoItemList[0].item.favorecido.id}');
			}
		});
	</script>
</c:if>

contames/src/main/webapp/WEB-INF/jsp/lancamento/lancamentoRateioList.jsp
<div id="layLancamentoRateioList">
	<c:if test="${lancamentoRateioList eq null or empty lancamentoRateioList}">
		<div class="alert alert-success text-center cm-table-notfound" role="alert">
			<strong>
				<i class="fa fa-info-circle"></i>
				<fmt:message key="nenhumRateioEncontrado"/>
			</strong>
		</div>
	</c:if>
	<c:if test="${lancamentoRateioList ne null and !empty lancamentoRateioList}">
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th class="cm-th"><fmt:message key="n_"/></th>
						<th class="cm-th"><fmt:message key="nome"/></th>
						<th class="cm-th">%</th>
						<th class="cm-th"><fmt:message key="valor"/></th>
					</tr>
				</thead>
				<tbody id="tbyLancamentoRateioList">
					<c:forEach var="lancamentoRateio" items="${lancamentoRateioList}">
						<tr data-id="${lancamentoRateio.id}" data-index="${lancamentoRateio.seq}" onclick="selecionaLancamentoRateio(this)" ondblclick="editarLancamentoRateio(this)">
							<td class="text-right">${lancamentoRateio.seq + 1}</td>
							<td><c:out value="${lancamentoRateio.displayNome}"/></td>
							<td class="text-right"><fmt:formatNumber type="number" value="${lancamentoRateio.perc}" maxFractionDigits="2" minFractionDigits="2" /></td>
							<td class="text-right"><fmt:formatNumber type="number" value="${lancamentoRateio.valor}" maxFractionDigits="2" minFractionDigits="2" /></td>
						</tr>
					</c:forEach>
				</tbody>
				<tfoot>
					<tr class="cm-tr-total">
						<td colspan="2" class="text-right"><fmt:message key="total"/> :</td>
						<td class="text-right"><fmt:formatNumber type="number" value="${lancamento.percLancamentoRateio}" maxFractionDigits="2" minFractionDigits="2" /></td>
						<td class="text-right"><fmt:formatNumber type="number" value="${lancamento.totalLancamentoRateio}" maxFractionDigits="2" minFractionDigits="2" /></td>
					</tr>
				</tfoot>
			</table>
		</div>
	</c:if>
</div>